general {
 disable_loading_bar = true
 hide_cursor = true
}
background {
 monitor =
 path = ~/.config/desktop/wallpapers/default.jpg
 blur_passes = 3
 blur_size = 8
 brightness = 0.55
}
label {
 monitor =
 text = cmd[update:1000] echo "$(date +'%H:%M')"
 font_family = JetBrainsMono Nerd Font
 font_size = 72
 color = rgb(cdd6f4)
 position = 0, 120
 halign = center
 valign = center
}
input-field {
 monitor =
 size = 320, 52
 outline_thickness = 2
 outer_color = rgb(89b4fa)
 inner_color = rgba(1e1e2eee)
 font_color = rgb(cdd6f4)
 placeholder_text = Contraseña
 position = 0, -40
 halign = center
 valign = center
}
